### ISSUE TITLE
[CORE/LUA] Improve `core.writeByte` documentation and/or offer alias with more telling names

### ISSUE THREAD

**Issue by TheRedDaemon** [UnofficialCrusaderPatch/UnofficialCrusaderPatch3#66]
I wanted to replace a byte like: `core.writeByte(address, 0xff)`  
However, this call caused a crash.  
`core.writeCode(address, { 0xff })` worked.

The cause is unknown to me. My guess would be that the write is not properly restricted to the byte, but I have no proof.

**Comment by gynt** [comment]
Implement: 
```lua
core.writeCodeByte
core.writeCodeBytes
core.writeCodeInteger
core.writeCoderShortInteger
```

**Comment by TheRedDaemon** [comment]
There is a typo in " writeCoderShortInteger". If they are copied from code, then the typo might also be there.
