### ISSUE TITLE
[AI_SWAPPER] Offer AI version update handling

### ISSUE THREAD

**Issue by TheRedDaemon** [UnofficialCrusaderPatch/UnofficialCrusaderPatch3#68]
The way depends on how the version handling develops.

**Comment by Krarilotus** [comment]
The way to make version compatibility excessible woudl be to allow path-names with astericses in the versions.
So it should probably support these in some form or another for changing file path names:
Original-Pluginname-*
Original-Pluginname-X.*
Original-Pluginname-X.X.*

**Comment by TheRedDaemon** [comment]
@gynt I have actually no idea how to solve this:
* I have no access to advanced semver structures in the custom menu.
* The backend at the moment needs the full path to know where to look. There may or may not be ways to construct it through other means, but there would still be another issue:
* Only the module + the ai uniquely identify the AI source, since the AI version is only displayed at the moment, not used in any way.
* No meta structure guarantees the uniqueness of AI name + AI version, they could come from multiple sources.
Any ideas?

**Comment by TheRedDaemon** [comment]
There can only be one version of a plugin/module loaded at any time, right?
If yes, if I could get the version of the currently active plugin in the backend, I might be able to construct the folder.
The same counts for the GUI: If only one plugin version can be active, I do not need to care for the version of the plugin in the swapper, since it can only be one AI of the same name per plugin.

**Comment by gynt** [comment]
> There can only be one version of a plugin/module loaded at any time, right? If yes, if I could get the version of the currently active plugin in the backend, I might be able to construct the folder. The same counts for the GUI: If only one plugin version can be active, I do not need to care for the version of the plugin in the swapper, since it can only be one AI of the same name per plugin.

Correct
